Marks the header up
NikKms/7team-mimino pull request #12
Opened 2023-02-16 13:50 UTC by BondarAV

2023-02-16 15:19 UTC, NikKms commented on src/partials/header.html
> +    <nav>
добавь классы сразу пожалуйста

2023-02-16 15:19 UTC, NikKms commented on src/partials/header.html
> +          <a href="">
переходы так-же добавь

2023-02-16 15:20 UTC, NikKms requested changes
Сделай сразу классы и ссылки на страницы отеля и кухни, спасибо

2023-02-16 15:42 UTC, BondarAV commented on src/partials/header.html
> +    <nav>
Николай, что на счет классов, они у меня простые, то есть, могут повторяться и у других ребят, но, я думаю, если все будут задавать стили на двойные селекторы, проблем возникнуть не должно? Или все же лучше написать классы посложнее?

2023-02-17 08:16 UTC, NikKms approved these changes

2023-02-17 08:16 UTC, merged